export type BlogInput={name:string;slug:string;niche:string;language:string;voice:string;domain?:string|null}
export type JobKind='niche'|'affiliate_radar'; export type JobStatus='draft'|'blocked'
export type DailyJob={id:string;blogId:string;kind:JobKind;status:JobStatus;title:string;bullets:string[];wordCount:number;ads:{affiliate:string|null;product:string|null};disclosure:string;keywords:string[];sources:string[]}
export interface BlogRepository { saveBlog(input:BlogInput):string; hasBlog(slug:string):boolean; saveAgent(blogId:string,profileId:string):void; saveHandoff(blogId:string,name:string):void; saveJobs(jobs:DailyJob[]):void; getBlog(id:string):BlogInput|undefined }
export interface HermesAdapter { createManager(input:BlogInput):{profileId:string;validated:boolean}; healthCheck(profileId:string):boolean }
export interface ControlTowerAdapter { provision(input:{name:string;slug:string;businessType:'custom';templateKey:'custom_base';domain?:string|null;language:string}):{projectId:string;schemaName:string;status:string} }
export interface FbrAdsAdapter { validateCreative(width:number,height:number):boolean }
export interface ImageProviderAdapter { source(query:string):{url:string;license:string} }
export class MockRepository implements BlogRepository { blogs=new Map<string,BlogInput>(); agents=new Map<string,string>(); handoffs:string[]=[]; jobs:DailyJob[]=[]; saveBlog(x:BlogInput){const id=crypto.randomUUID();this.blogs.set(id,x);return id} hasBlog(slug:string){return [...this.blogs.values()].some(x=>x.slug===slug)} saveAgent(id:string,p:string){this.agents.set(id,p)} saveHandoff(id:string,n:string){this.handoffs.push(`${id}:${n}`)} saveJobs(x:DailyJob[]){this.jobs.push(...x)} getBlog(id:string){return this.blogs.get(id)} }
export class MockHermes implements HermesAdapter { constructor(private valid=true){} createManager(_:BlogInput){return {profileId:`hermes-manager-${crypto.randomUUID()}`,validated:this.valid}} healthCheck(_:string){return this.valid} }
export class MockControlTower implements ControlTowerAdapter {calls=0; provision(x:{slug:string}){this.calls++;return {projectId:`ct-${x.slug}`,schemaName:`custom_${x.slug}`,status:'provisioned'}}}
export class BlogService { constructor(private repo:BlogRepository,private hermes:HermesAdapter,private tower:ControlTowerAdapter){}
 async createBlog(input:BlogInput){if(!/^[a-z0-9_]+$/.test(input.slug))throw new Error('invalid slug');if(this.repo.hasBlog(input.slug))throw new Error('duplicate slug');const id=this.repo.saveBlog(input);const manager=this.hermes.createManager(input);this.repo.saveAgent(id,manager.profileId);if(!manager.validated||!this.hermes.healthCheck(manager.profileId))throw new Error('manager must be validated');const project=this.tower.provision({name:input.name,slug:input.slug,businessType:'custom',templateKey:'custom_base',domain:input.domain??null,language:input.language});for(const h of ['developer-doc','frontend-adsense-handoff','bigwriter-handoff'])this.repo.saveHandoff(id,h);return {blogId:id,projectId:project.projectId,schemaName:project.schemaName,templateKey:'custom_base',handoffs:['developer-doc','frontend-adsense-handoff','bigwriter-handoff']}}
 dailyRun(blogId:string){if(!this.repo.getBlog(blogId))throw new Error('blog not found');const kinds:JobKind[]=['niche','niche','affiliate_radar'];const jobs=kinds.map((kind,i)=>({id:crypto.randomUUID(),blogId,kind,status:'draft' as const,title:kind==='affiliate_radar'?'Radar de Afiliados: oportunidade do nicho':'Guia editorial do nicho',bullets:['contexto factual','tendência relevante','análise prática','próximos passos'],wordCount:1300,ads:{affiliate:'affiliate-ad-1',product:'product-ad-1'},disclosure:'Este artigo pode conter links afiliados; podemos receber comissão sem custo adicional.',keywords:['nicho','guia','tendências'],sources:['https://example.com/source'],}));this.repo.saveJobs(jobs);return jobs}}
export const fbrAdsFormats=[{width:1250,height:150},{width:350,height:350}]
export class MockFbrAds implements FbrAdsAdapter {validateCreative(w:number,h:number){return fbrAdsFormats.some(x=>x.width===w&&x.height===h)}}
export class MockImageProvider implements ImageProviderAdapter {source(q:string){return {url:`mock://image/${encodeURIComponent(q)}`,license:'mock-license'}}}
